#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# On the 9th iteration, displays "Hi" before "Best School".
n=0
while [ $n -lt 10 ]
do
	if [ $n -eq 9 ]
	then
	 echo "Hi"
	fi
	 echo "Best School"
	(( n++ ))
done
 
