#!/usr/bin/env bash
# This script is displaying 1 to 20 
# displays 4 and then bad luck from china  On the 4th loop iteration.
# displays 9 and then bad luck from japan On the 9th loop iteration.
# displays 17 and then bad luck from italy On the 9th loop iteration.


n=1
 while [ $n -lt 20 ]
 do
 echo "$n"
 case $n in
	"4") echo " bad luck from china ";;
	"9") echo " bad luck from japan ";;
	"17") echo "bad luck from italy";;
   esac
         (( n++ ))
done
