#!/usr/bin/env bash
#configure ufw to block all incoming traffic with exception of TCP ports 22, 443, 80

apt-get install ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable
